---
title: "Duke's Ohio St Loss Analysis"
author: '@jonmichaelstroh'
date: "12/1/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, 
                      echo = TRUE, dpi = 300, cache.lazy = FALSE,
                      tidy = "styler")
```

```{r load libraries}
library(tidyverse)
library(dplyr)
library(gamezoneR)
library(Rcpp)
library(ggplot2)
library(ggimage)
library(imager)
library(knitr)
```

```{r}
duke_schedule <-  gamezone_mbb_team_schedule("Duke", season = '2021-22')
```

```{r get player's shots}
duke_shots_ohio_st <- purrr::map_df('2373048', 
                          gamezone_mbb_pbp, sub_parse = F)
```

A quick shooting analysis of Duke's painful loss to Ohio St :(

#first half
```{r}
dsos_first_half <- duke_shots_ohio_st %>% filter(half == 1) %>% filter(!is.na(shooter)) %>% filter(event_team == 'Duke')

dsos_first_half <- dsos_first_half %>% mutate(loc_x = if_else(shot_desc=='Layup Shot', loc_x + runif(n(), -2.5, 2.5), loc_x)) %>% mutate(loc_y = if_else(shot_desc=='Layup Shot', loc_y + runif(n(), -1, 2.5), loc_y))


gamezoneR::base_court +
geom_point(data = dsos_first_half, aes(loc_x, loc_y, color = shot_outcome), shape = 19, size = 2.5) + scale_color_manual(breaks = c("made", "missed"), values=c('#00539B', "#FF160C")) + theme(legend.position = "none", plot.background = element_rect(fill = '#EFEFEF')) + annotate('text', label = 'efficient near the basket', x = 25, y = 3, color = '#00539B' )
```

#second half pre 7:20
```{r}
dsos_second_half <- duke_shots_ohio_st %>% filter(half == 2) %>% filter(!is.na(shooter)) %>% filter(event_team == 'Duke')

dsos_second_half <- dsos_second_half %>% mutate(loc_x = if_else(shot_desc=='Layup Shot', loc_x + runif(n(), -2.5, 2.5), loc_x)) %>% mutate(loc_y = if_else(shot_desc=='Layup Shot', loc_y + runif(n(), -1, 2.5), loc_y))

gamezoneR::base_court +
geom_point(data = dsos_second_half, aes(loc_x, loc_y, color = shot_outcome), shape = 19, size = 2.5) + scale_color_manual(breaks = c("made", "missed"), values=c('#00539B', "#FF160C")) + theme(legend.position = "none", plot.background = element_rect(fill = '#EFEFEF')) + annotate('text', label = 'lotta right wing bricks', x = 11.25, y = 31, color = '#FF160C' )
```

#final 7:20

```{r}
dsos_final720 <- duke_shots_ohio_st %>% filter(game_secs_remaining < 420) %>% filter(!is.na(shooter)) %>% filter(event_team == 'Duke')

dsos_final720 <- dsos_final720 %>% mutate(loc_x = if_else(shot_desc=='Layup Shot', loc_x + runif(n(), -2.5, 2.5), loc_x)) %>% mutate(loc_y = if_else(shot_desc=='Layup Shot', loc_y + runif(n(), -1, 2.5), loc_y))

#pain
gamezoneR::base_court +
geom_point(data = duke_final720, aes(loc_x, loc_y, color = shot_outcome), shape = 19, size = 2.5) + scale_color_manual(breaks = c("made", "missed"), values=c('#00539B', "#FF160C")) + theme(legend.position = "none", plot.background = element_rect(fill = '#EFEFEF'))
```


```{r Shot Chart}
gamezoneR::base_court +
geom_point(data = duke_shots_ohio_st, aes(loc_x, loc_y, color = shot_outcome), shape = 19, size = 2.5) + scale_color_manual(breaks = c("made", "missed"), values=c('#00539B', "#FF160C")) + theme(legend.position = "none", plot.background = element_rect(fill = 'light blue'))
```



### GGimage
```{r}
library(png)
```

```{r}
duke_shots_ohio_st <- duke_shots_ohio_st %>% mutate(image = if_else(shot_outcome == "made", "bball.png", "brick.png"))
```


#Little tangent to practice drawing a court

```{r}
width = 50
height = 94 / 2
key_height = 19
inner_key_width = 12
outer_key_width = 12 
backboard_width = 6
backboard_offset = 4
neck_length = 0.5
hoop_radius = 0.75
hoop_center_y = backboard_offset + neck_length + hoop_radius
three_point_radius = 23.75
three_point_side_radius = 22
three_point_side_height = 14

circle_points = function(center = c(0, 0), radius = 1, npoints = 360) {
  angles = seq(0, 2 * pi, length.out = npoints)
  return(dplyr::tibble(x = center[1] + radius * cos(angles),
                       y = center[2] + radius * sin(angles)))
}

three_point_circle = circle_points(center = c(0, hoop_center_y), radius = three_point_radius) %>%
    dplyr::filter(y >= three_point_side_height, y >= hoop_center_y)

three_point_line = dplyr::tibble(
    x = c(three_point_side_radius, three_point_side_radius, three_point_circle$x, -three_point_side_radius, -three_point_side_radius),
    y = c(0, three_point_side_height, three_point_circle$y, three_point_side_height, 0),
    desc = "three_point_line")

 court_points = three_point_line %>% mutate(x = x + 25)
```  


```{r}
ggplot(duke_shots_ohio_st, aes(loc_x, loc_y)) + geom_image(aes(image = image)) + geom_path(data = court_points,
                       aes(x = x, y = y, group = desc),
                       color = 'blue', size = 2)
```

```{r}
ggplot(duke_shots_ohio_st, aes(loc_x, loc_y)) + geom_emoji(aes(image = if_else(shot_outcome == 'missed', '1f622', '1f600'))) + geom_path(data = court_points,
                       aes(x = x, y = y, group = desc),
                       color = 'blue', size = 2)
```

OK haha...that's enough practice for one day.  Not Kirk Goldsberry just yet.




